###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 81
###网关名称
spring:
  application:
    name: service-zuul
  cloud:
      config:
      ####读取后缀
        profile: dev
        ####读取config-server注册地址
        discovery:
  #      需要和configServer  spring-application-name中的名称一致
          service-id: config-server
          enabled: true
#### 配置网关反向代理
#zuul:
#  routes:
#    api-a:
#     ### 以 /api-member/访问转发到会员服务
#      path: /api-member/**
##      zuul网关默认整合ribbon 自动实现负载均衡轮循效果  默认30s
#      serviceId: app-springcloud-member
#    api-b:
#        ### 以 /api-order/访问转发到订单服务
#      path: /api-order/**
#      serviceId: app-springcloud-order

###开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"